CREATE TABLE IF NOT EXISTS  `user` (
`id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
`Uid` varchar(45) NOT NULL COMMENT '玩家唯一ID',
`Forever` varchar(2000) NOT NULL COMMENT '永久存储',
PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户表';