// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.3
// source: pb/rank.proto

package msg

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RankClient is the client API for Rank service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RankClient interface {
	Pull(ctx context.Context, in *RankPullRequest, opts ...grpc.CallOption) (*RankPullReply, error)
	Update(ctx context.Context, in *RankUpdateRequest, opts ...grpc.CallOption) (*RankUpdateReply, error)
	Self(ctx context.Context, in *RankSelfRequest, opts ...grpc.CallOption) (*RankMember, error)
}

type rankClient struct {
	cc grpc.ClientConnInterface
}

func NewRankClient(cc grpc.ClientConnInterface) RankClient {
	return &rankClient{cc}
}

func (c *rankClient) Pull(ctx context.Context, in *RankPullRequest, opts ...grpc.CallOption) (*RankPullReply, error) {
	out := new(RankPullReply)
	err := c.cc.Invoke(ctx, "/msg.Rank/Pull", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rankClient) Update(ctx context.Context, in *RankUpdateRequest, opts ...grpc.CallOption) (*RankUpdateReply, error) {
	out := new(RankUpdateReply)
	err := c.cc.Invoke(ctx, "/msg.Rank/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rankClient) Self(ctx context.Context, in *RankSelfRequest, opts ...grpc.CallOption) (*RankMember, error) {
	out := new(RankMember)
	err := c.cc.Invoke(ctx, "/msg.Rank/Self", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RankServer is the server API for Rank service.
// All implementations must embed UnimplementedRankServer
// for forward compatibility
type RankServer interface {
	Pull(context.Context, *RankPullRequest) (*RankPullReply, error)
	Update(context.Context, *RankUpdateRequest) (*RankUpdateReply, error)
	Self(context.Context, *RankSelfRequest) (*RankMember, error)
	mustEmbedUnimplementedRankServer()
}

// UnimplementedRankServer must be embedded to have forward compatible implementations.
type UnimplementedRankServer struct {
}

func (UnimplementedRankServer) Pull(context.Context, *RankPullRequest) (*RankPullReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pull not implemented")
}
func (UnimplementedRankServer) Update(context.Context, *RankUpdateRequest) (*RankUpdateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedRankServer) Self(context.Context, *RankSelfRequest) (*RankMember, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Self not implemented")
}
func (UnimplementedRankServer) mustEmbedUnimplementedRankServer() {}

// UnsafeRankServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RankServer will
// result in compilation errors.
type UnsafeRankServer interface {
	mustEmbedUnimplementedRankServer()
}

func RegisterRankServer(s grpc.ServiceRegistrar, srv RankServer) {
	s.RegisterService(&Rank_ServiceDesc, srv)
}

func _Rank_Pull_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RankPullRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankServer).Pull(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/msg.Rank/Pull",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankServer).Pull(ctx, req.(*RankPullRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rank_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RankUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/msg.Rank/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankServer).Update(ctx, req.(*RankUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rank_Self_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RankSelfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankServer).Self(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/msg.Rank/Self",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankServer).Self(ctx, req.(*RankSelfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Rank_ServiceDesc is the grpc.ServiceDesc for Rank service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Rank_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "msg.Rank",
	HandlerType: (*RankServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Pull",
			Handler:    _Rank_Pull_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Rank_Update_Handler,
		},
		{
			MethodName: "Self",
			Handler:    _Rank_Self_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/rank.proto",
}
