// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: pb/rank.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RankSelfRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RankSelfRequest) Reset() {
	*x = RankSelfRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_rank_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RankSelfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankSelfRequest) ProtoMessage() {}

func (x *RankSelfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rank_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankSelfRequest.ProtoReflect.Descriptor instead.
func (*RankSelfRequest) Descriptor() ([]byte, []int) {
	return file_pb_rank_proto_rawDescGZIP(), []int{0}
}

type RankPullRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RankPullRequest) Reset() {
	*x = RankPullRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_rank_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RankPullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankPullRequest) ProtoMessage() {}

func (x *RankPullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rank_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankPullRequest.ProtoReflect.Descriptor instead.
func (*RankPullRequest) Descriptor() ([]byte, []int) {
	return file_pb_rank_proto_rawDescGZIP(), []int{1}
}

type RankPullReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Members []*RankMember `protobuf:"bytes,1,rep,name=Members,proto3" json:"Members,omitempty"`
}

func (x *RankPullReply) Reset() {
	*x = RankPullReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_rank_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RankPullReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankPullReply) ProtoMessage() {}

func (x *RankPullReply) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rank_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankPullReply.ProtoReflect.Descriptor instead.
func (*RankPullReply) Descriptor() ([]byte, []int) {
	return file_pb_rank_proto_rawDescGZIP(), []int{2}
}

func (x *RankPullReply) GetMembers() []*RankMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type RankUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid      string `protobuf:"bytes,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Nickname string `protobuf:"bytes,2,opt,name=Nickname,proto3" json:"Nickname,omitempty"`
	Icon     string `protobuf:"bytes,3,opt,name=Icon,proto3" json:"Icon,omitempty"`
	Val      int32  `protobuf:"varint,4,opt,name=Val,proto3" json:"Val,omitempty"`
}

func (x *RankUpdateRequest) Reset() {
	*x = RankUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_rank_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RankUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankUpdateRequest) ProtoMessage() {}

func (x *RankUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rank_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankUpdateRequest.ProtoReflect.Descriptor instead.
func (*RankUpdateRequest) Descriptor() ([]byte, []int) {
	return file_pb_rank_proto_rawDescGZIP(), []int{3}
}

func (x *RankUpdateRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *RankUpdateRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *RankUpdateRequest) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *RankUpdateRequest) GetVal() int32 {
	if x != nil {
		return x.Val
	}
	return 0
}

type RankMember struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid          string `protobuf:"bytes,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Nickname     string `protobuf:"bytes,2,opt,name=Nickname,proto3" json:"Nickname,omitempty"`
	Icon         string `protobuf:"bytes,3,opt,name=Icon,proto3" json:"Icon,omitempty"`
	Val          int32  `protobuf:"varint,4,opt,name=Val,proto3" json:"Val,omitempty"`
	Country      string `protobuf:"bytes,5,opt,name=Country,proto3" json:"Country,omitempty"`
	CountryShort string `protobuf:"bytes,6,opt,name=CountryShort,proto3" json:"CountryShort,omitempty"`
}

func (x *RankMember) Reset() {
	*x = RankMember{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_rank_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RankMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankMember) ProtoMessage() {}

func (x *RankMember) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rank_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankMember.ProtoReflect.Descriptor instead.
func (*RankMember) Descriptor() ([]byte, []int) {
	return file_pb_rank_proto_rawDescGZIP(), []int{4}
}

func (x *RankMember) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *RankMember) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *RankMember) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *RankMember) GetVal() int32 {
	if x != nil {
		return x.Val
	}
	return 0
}

func (x *RankMember) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *RankMember) GetCountryShort() string {
	if x != nil {
		return x.CountryShort
	}
	return ""
}

type RankUpdateReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State bool `protobuf:"varint,1,opt,name=State,proto3" json:"State,omitempty"`
}

func (x *RankUpdateReply) Reset() {
	*x = RankUpdateReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_rank_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RankUpdateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankUpdateReply) ProtoMessage() {}

func (x *RankUpdateReply) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rank_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankUpdateReply.ProtoReflect.Descriptor instead.
func (*RankUpdateReply) Descriptor() ([]byte, []int) {
	return file_pb_rank_proto_rawDescGZIP(), []int{5}
}

func (x *RankUpdateReply) GetState() bool {
	if x != nil {
		return x.State
	}
	return false
}

var File_pb_rank_proto protoreflect.FileDescriptor

var file_pb_rank_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x62, 0x2f, 0x72, 0x61, 0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x6d, 0x73, 0x67, 0x22, 0x11, 0x0a, 0x0f, 0x52, 0x61, 0x6e, 0x6b, 0x53, 0x65, 0x6c, 0x66,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x52, 0x61, 0x6e, 0x6b, 0x50,
	0x75, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3a, 0x0a, 0x0d, 0x52, 0x61,
	0x6e, 0x6b, 0x50, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x29, 0x0a, 0x07, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d,
	0x73, 0x67, 0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x07, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x22, 0x67, 0x0a, 0x11, 0x52, 0x61, 0x6e, 0x6b, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x55,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x69, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x49, 0x63, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x49, 0x63, 0x6f, 0x6e, 0x12, 0x10, 0x0a,
	0x03, 0x56, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x56, 0x61, 0x6c, 0x22,
	0x9e, 0x01, 0x0a, 0x0a, 0x52, 0x61, 0x6e, 0x6b, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x10,
	0x0a, 0x03, 0x55, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x69, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x49, 0x63, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x49, 0x63, 0x6f, 0x6e,
	0x12, 0x10, 0x0a, 0x03, 0x56, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x56,
	0x61, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x22, 0x0a, 0x0c,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x53, 0x68, 0x6f, 0x72, 0x74,
	0x22, 0x27, 0x0a, 0x0f, 0x52, 0x61, 0x6e, 0x6b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x32, 0xa5, 0x01, 0x0a, 0x04, 0x52, 0x61,
	0x6e, 0x6b, 0x12, 0x32, 0x0a, 0x04, 0x50, 0x75, 0x6c, 0x6c, 0x12, 0x14, 0x2e, 0x6d, 0x73, 0x67,
	0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x50, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x12, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x50, 0x75, 0x6c, 0x6c, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x12, 0x16, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x52,
	0x61, 0x6e, 0x6b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00,
	0x12, 0x2f, 0x0a, 0x04, 0x53, 0x65, 0x6c, 0x66, 0x12, 0x14, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x52,
	0x61, 0x6e, 0x6b, 0x53, 0x65, 0x6c, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f,
	0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x22,
	0x00, 0x42, 0x06, 0x5a, 0x04, 0x2f, 0x6d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_pb_rank_proto_rawDescOnce sync.Once
	file_pb_rank_proto_rawDescData = file_pb_rank_proto_rawDesc
)

func file_pb_rank_proto_rawDescGZIP() []byte {
	file_pb_rank_proto_rawDescOnce.Do(func() {
		file_pb_rank_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_rank_proto_rawDescData)
	})
	return file_pb_rank_proto_rawDescData
}

var file_pb_rank_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pb_rank_proto_goTypes = []interface{}{
	(*RankSelfRequest)(nil),   // 0: msg.RankSelfRequest
	(*RankPullRequest)(nil),   // 1: msg.RankPullRequest
	(*RankPullReply)(nil),     // 2: msg.RankPullReply
	(*RankUpdateRequest)(nil), // 3: msg.RankUpdateRequest
	(*RankMember)(nil),        // 4: msg.RankMember
	(*RankUpdateReply)(nil),   // 5: msg.RankUpdateReply
}
var file_pb_rank_proto_depIdxs = []int32{
	4, // 0: msg.RankPullReply.Members:type_name -> msg.RankMember
	1, // 1: msg.Rank.Pull:input_type -> msg.RankPullRequest
	3, // 2: msg.Rank.Update:input_type -> msg.RankUpdateRequest
	0, // 3: msg.Rank.Self:input_type -> msg.RankSelfRequest
	2, // 4: msg.Rank.Pull:output_type -> msg.RankPullReply
	5, // 5: msg.Rank.Update:output_type -> msg.RankUpdateReply
	4, // 6: msg.Rank.Self:output_type -> msg.RankMember
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_rank_proto_init() }
func file_pb_rank_proto_init() {
	if File_pb_rank_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_rank_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RankSelfRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_rank_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RankPullRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_rank_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RankPullReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_rank_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RankUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_rank_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RankMember); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_rank_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RankUpdateReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_rank_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_rank_proto_goTypes,
		DependencyIndexes: file_pb_rank_proto_depIdxs,
		MessageInfos:      file_pb_rank_proto_msgTypes,
	}.Build()
	File_pb_rank_proto = out.File
	file_pb_rank_proto_rawDesc = nil
	file_pb_rank_proto_goTypes = nil
	file_pb_rank_proto_depIdxs = nil
}
