// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: pb/room.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Member *Member `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"` // 成员信息
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_room_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_room_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_pb_room_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRoomRequest) GetMember() *Member {
	if x != nil {
		return x.Member
	}
	return nil
}

type MatchRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomID int32 `protobuf:"varint,1,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
}

func (x *MatchRoomRequest) Reset() {
	*x = MatchRoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_room_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchRoomRequest) ProtoMessage() {}

func (x *MatchRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_room_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchRoomRequest.ProtoReflect.Descriptor instead.
func (*MatchRoomRequest) Descriptor() ([]byte, []int) {
	return file_pb_room_proto_rawDescGZIP(), []int{1}
}

func (x *MatchRoomRequest) GetRoomID() int32 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

type OfflineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=Uuid,proto3" json:"Uuid,omitempty"` // 离线玩家的uuid信息
}

func (x *OfflineRequest) Reset() {
	*x = OfflineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_room_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OfflineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfflineRequest) ProtoMessage() {}

func (x *OfflineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_room_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfflineRequest.ProtoReflect.Descriptor instead.
func (*OfflineRequest) Descriptor() ([]byte, []int) {
	return file_pb_room_proto_rawDescGZIP(), []int{2}
}

func (x *OfflineRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type MatchMemberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Member *Member `protobuf:"bytes,1,opt,name=Member,proto3" json:"Member,omitempty"` // 匹配人信息
}

func (x *MatchMemberRequest) Reset() {
	*x = MatchMemberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_room_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchMemberRequest) ProtoMessage() {}

func (x *MatchMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_room_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchMemberRequest.ProtoReflect.Descriptor instead.
func (*MatchMemberRequest) Descriptor() ([]byte, []int) {
	return file_pb_room_proto_rawDescGZIP(), []int{3}
}

func (x *MatchMemberRequest) GetMember() *Member {
	if x != nil {
		return x.Member
	}
	return nil
}

type AddRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomID int32   `protobuf:"varint,2,opt,name=RoomID,proto3" json:"RoomID,omitempty"` // 要加入的房间ID
	Member *Member `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`  // 要加入的成员
}

func (x *AddRequest) Reset() {
	*x = AddRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_room_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRequest) ProtoMessage() {}

func (x *AddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_room_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRequest.ProtoReflect.Descriptor instead.
func (*AddRequest) Descriptor() ([]byte, []int) {
	return file_pb_room_proto_rawDescGZIP(), []int{4}
}

func (x *AddRequest) GetRoomID() int32 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

func (x *AddRequest) GetMember() *Member {
	if x != nil {
		return x.Member
	}
	return nil
}

type LeaveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomID int32   `protobuf:"varint,2,opt,name=RoomID,proto3" json:"RoomID,omitempty"` // 要加入的房间ID
	Member *Member `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`  // 要加入的成员
}

func (x *LeaveRequest) Reset() {
	*x = LeaveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_room_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRequest) ProtoMessage() {}

func (x *LeaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_room_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRequest.ProtoReflect.Descriptor instead.
func (*LeaveRequest) Descriptor() ([]byte, []int) {
	return file_pb_room_proto_rawDescGZIP(), []int{5}
}

func (x *LeaveRequest) GetRoomID() int32 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

func (x *LeaveRequest) GetMember() *Member {
	if x != nil {
		return x.Member
	}
	return nil
}

type OverRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomID int32   `protobuf:"varint,2,opt,name=RoomID,proto3" json:"RoomID,omitempty"` // 要加入的房间ID
	Member *Member `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`  // 要加入的成员
}

func (x *OverRequest) Reset() {
	*x = OverRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_room_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverRequest) ProtoMessage() {}

func (x *OverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_room_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverRequest.ProtoReflect.Descriptor instead.
func (*OverRequest) Descriptor() ([]byte, []int) {
	return file_pb_room_proto_rawDescGZIP(), []int{6}
}

func (x *OverRequest) GetRoomID() int32 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

func (x *OverRequest) GetMember() *Member {
	if x != nil {
		return x.Member
	}
	return nil
}

type Answer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomID     int32   `protobuf:"varint,1,opt,name=RoomID,proto3" json:"RoomID,omitempty"`         // 对应的房间ID
	Member     *Member `protobuf:"bytes,2,opt,name=Member,proto3" json:"Member,omitempty"`          // 回答问题的人
	QuestionID int32   `protobuf:"varint,3,opt,name=QuestionID,proto3" json:"QuestionID,omitempty"` // 问题ID
	Result     string  `protobuf:"bytes,4,opt,name=Result,proto3" json:"Result,omitempty"`          // 回答结果
}

func (x *Answer) Reset() {
	*x = Answer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_room_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Answer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer) ProtoMessage() {}

func (x *Answer) ProtoReflect() protoreflect.Message {
	mi := &file_pb_room_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer.ProtoReflect.Descriptor instead.
func (*Answer) Descriptor() ([]byte, []int) {
	return file_pb_room_proto_rawDescGZIP(), []int{7}
}

func (x *Answer) GetRoomID() int32 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

func (x *Answer) GetMember() *Member {
	if x != nil {
		return x.Member
	}
	return nil
}

func (x *Answer) GetQuestionID() int32 {
	if x != nil {
		return x.QuestionID
	}
	return 0
}

func (x *Answer) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type Question struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID          int32  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`                  // 题库ID
	Question    string `protobuf:"bytes,2,opt,name=Question,proto3" json:"Question,omitempty"`       // 问题
	AnswerA     string `protobuf:"bytes,3,opt,name=AnswerA,proto3" json:"AnswerA,omitempty"`         // 答案A
	AnswerB     string `protobuf:"bytes,4,opt,name=AnswerB,proto3" json:"AnswerB,omitempty"`         // 答案B
	AnswerC     string `protobuf:"bytes,5,opt,name=AnswerC,proto3" json:"AnswerC,omitempty"`         // 答案C
	AnswerD     string `protobuf:"bytes,6,opt,name=AnswerD,proto3" json:"AnswerD,omitempty"`         // 答案D
	RightAnswer string `protobuf:"bytes,7,opt,name=RightAnswer,proto3" json:"RightAnswer,omitempty"` // 正确答案
}

func (x *Question) Reset() {
	*x = Question{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_room_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_pb_room_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_pb_room_proto_rawDescGZIP(), []int{8}
}

func (x *Question) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Question) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *Question) GetAnswerA() string {
	if x != nil {
		return x.AnswerA
	}
	return ""
}

func (x *Question) GetAnswerB() string {
	if x != nil {
		return x.AnswerB
	}
	return ""
}

func (x *Question) GetAnswerC() string {
	if x != nil {
		return x.AnswerC
	}
	return ""
}

func (x *Question) GetAnswerD() string {
	if x != nil {
		return x.AnswerD
	}
	return ""
}

func (x *Question) GetRightAnswer() string {
	if x != nil {
		return x.RightAnswer
	}
	return ""
}

type Member struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid     string    `protobuf:"bytes,1,opt,name=Uuid,proto3" json:"Uuid,omitempty"`          // 用户服务端uuid
	Uid      string    `protobuf:"bytes,2,opt,name=Uid,proto3" json:"Uid,omitempty"`            // 用户Uid
	Nickname string    `protobuf:"bytes,3,opt,name=Nickname,proto3" json:"Nickname,omitempty"`  // 用户昵称
	Icon     string    `protobuf:"bytes,4,opt,name=Icon,proto3" json:"Icon,omitempty"`          // 用户头像
	IsMaster bool      `protobuf:"varint,5,opt,name=IsMaster,proto3" json:"IsMaster,omitempty"` // 是否房主
	IsRobot  bool      `protobuf:"varint,6,opt,name=IsRobot,proto3" json:"IsRobot,omitempty"`   // 是否是机器人
	Answer   []*Answer `protobuf:"bytes,7,rep,name=Answer,proto3" json:"Answer,omitempty"`      // 回答
}

func (x *Member) Reset() {
	*x = Member{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_room_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_pb_room_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_pb_room_proto_rawDescGZIP(), []int{9}
}

func (x *Member) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Member) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Member) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *Member) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *Member) GetIsMaster() bool {
	if x != nil {
		return x.IsMaster
	}
	return false
}

func (x *Member) GetIsRobot() bool {
	if x != nil {
		return x.IsRobot
	}
	return false
}

func (x *Member) GetAnswer() []*Answer {
	if x != nil {
		return x.Answer
	}
	return nil
}

type CreateRoomReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomID         int32     `protobuf:"varint,1,opt,name=RoomID,proto3" json:"RoomID,omitempty"`                // 房间ID
	PrepareMembers []*Member `protobuf:"bytes,2,rep,name=PrepareMembers,proto3" json:"PrepareMembers,omitempty"` // 准备成员列表
	PlayingMembers []*Member `protobuf:"bytes,3,rep,name=PlayingMembers,proto3" json:"PlayingMembers,omitempty"` // 准备成员列表
	Progress       int32     `protobuf:"varint,4,opt,name=Progress,proto3" json:"Progress,omitempty"`            // 当前进程(时间秒)
	MsgID          int32     `protobuf:"varint,5,opt,name=MsgID,proto3" json:"MsgID,omitempty"`                  // 消息ID
	ChangeMemeber  *Member   `protobuf:"bytes,6,opt,name=ChangeMemeber,proto3" json:"ChangeMemeber,omitempty"`   // 变更成员
	Question       *Question `protobuf:"bytes,7,opt,name=Question,proto3" json:"Question,omitempty"`             // 问题
}

func (x *CreateRoomReply) Reset() {
	*x = CreateRoomReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_room_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRoomReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomReply) ProtoMessage() {}

func (x *CreateRoomReply) ProtoReflect() protoreflect.Message {
	mi := &file_pb_room_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomReply.ProtoReflect.Descriptor instead.
func (*CreateRoomReply) Descriptor() ([]byte, []int) {
	return file_pb_room_proto_rawDescGZIP(), []int{10}
}

func (x *CreateRoomReply) GetRoomID() int32 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

func (x *CreateRoomReply) GetPrepareMembers() []*Member {
	if x != nil {
		return x.PrepareMembers
	}
	return nil
}

func (x *CreateRoomReply) GetPlayingMembers() []*Member {
	if x != nil {
		return x.PlayingMembers
	}
	return nil
}

func (x *CreateRoomReply) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *CreateRoomReply) GetMsgID() int32 {
	if x != nil {
		return x.MsgID
	}
	return 0
}

func (x *CreateRoomReply) GetChangeMemeber() *Member {
	if x != nil {
		return x.ChangeMemeber
	}
	return nil
}

func (x *CreateRoomReply) GetQuestion() *Question {
	if x != nil {
		return x.Question
	}
	return nil
}

type RoomChangeState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State int32 `protobuf:"varint,1,opt,name=State,proto3" json:"State,omitempty"`
}

func (x *RoomChangeState) Reset() {
	*x = RoomChangeState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_room_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomChangeState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomChangeState) ProtoMessage() {}

func (x *RoomChangeState) ProtoReflect() protoreflect.Message {
	mi := &file_pb_room_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomChangeState.ProtoReflect.Descriptor instead.
func (*RoomChangeState) Descriptor() ([]byte, []int) {
	return file_pb_room_proto_rawDescGZIP(), []int{11}
}

func (x *RoomChangeState) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

var File_pb_room_proto protoreflect.FileDescriptor

var file_pb_room_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x62, 0x2f, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x6d, 0x73, 0x67, 0x22, 0x38, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f,
	0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x06, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x73, 0x67, 0x2e,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x2a,
	0x0a, 0x10, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x22, 0x24, 0x0a, 0x0e, 0x4f, 0x66,
	0x66, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x55, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x55, 0x75, 0x69, 0x64,
	0x22, 0x39, 0x0a, 0x12, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x06, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x52, 0x06, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x49, 0x0a, 0x0a, 0x41,
	0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6f,
	0x6d, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49,
	0x44, 0x12, 0x23, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x06,
	0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x4b, 0x0a, 0x0c, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x12, 0x23,
	0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x06, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x22, 0x4a, 0x0a, 0x0b, 0x4f, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x12, 0x23, 0x0a, 0x06, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x73, 0x67,
	0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x22,
	0x7d, 0x0a, 0x06, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6f,
	0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49,
	0x44, 0x12, 0x23, 0x0a, 0x06, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x06,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x51, 0x75, 0x65, 0x73,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0xc0,
	0x01, 0x0a, 0x08, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x51,
	0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x51,
	0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x41, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72,
	0x41, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x42, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x42, 0x12, 0x18, 0x0a, 0x07, 0x41,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x43, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x6e,
	0x73, 0x77, 0x65, 0x72, 0x43, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x44,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x44, 0x12,
	0x20, 0x0a, 0x0b, 0x52, 0x69, 0x67, 0x68, 0x74, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x52, 0x69, 0x67, 0x68, 0x74, 0x41, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x22, 0xb9, 0x01, 0x0a, 0x06, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x55, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x55, 0x75, 0x69, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x55, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55,
	0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x49, 0x63, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x49, 0x63,
	0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x49, 0x73, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x49, 0x73, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x12, 0x18,
	0x0a, 0x07, 0x49, 0x73, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x49, 0x73, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x12, 0x23, 0x0a, 0x06, 0x41, 0x6e, 0x73, 0x77,
	0x65, 0x72, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x41,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x06, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x22, 0xa3, 0x02,
	0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x12, 0x33, 0x0a, 0x0e, 0x50, 0x72, 0x65,
	0x70, 0x61, 0x72, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x0e,
	0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x33,
	0x0a, 0x0e, 0x50, 0x6c, 0x61, 0x79, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x52, 0x0e, 0x50, 0x6c, 0x61, 0x79, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x4d, 0x73, 0x67, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x4d, 0x73, 0x67, 0x49, 0x44, 0x12, 0x31, 0x0a, 0x0d, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4d,
	0x65, 0x6d, 0x65, 0x62, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d,
	0x73, 0x67, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x0d, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x4d, 0x65, 0x6d, 0x65, 0x62, 0x65, 0x72, 0x12, 0x29, 0x0a, 0x08, 0x51, 0x75, 0x65, 0x73,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x73, 0x67,
	0x2e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x51, 0x75, 0x65, 0x73, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x27, 0x0a, 0x0f, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x32, 0xc5, 0x04, 0x0a,
	0x04, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x3a, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12,
	0x16, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x30,
	0x01, 0x12, 0x2e, 0x0a, 0x03, 0x41, 0x64, 0x64, 0x12, 0x0f, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x41,
	0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x6d, 0x73, 0x67, 0x2e,
	0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22,
	0x00, 0x12, 0x32, 0x0a, 0x05, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x12, 0x11, 0x2e, 0x6d, 0x73, 0x67,
	0x2e, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e,
	0x6d, 0x73, 0x67, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x22, 0x00, 0x12, 0x30, 0x0a, 0x04, 0x4f, 0x76, 0x65, 0x72, 0x12, 0x10, 0x2e,
	0x6d, 0x73, 0x67, 0x2e, 0x4f, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x14, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x0e, 0x41, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0b, 0x2e, 0x6d, 0x73, 0x67, 0x2e,
	0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x1a, 0x14, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x52, 0x6f, 0x6f,
	0x6d, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x00, 0x12, 0x3a,
	0x0a, 0x09, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x15, 0x2e, 0x6d, 0x73,
	0x67, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x14, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x0b, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x17, 0x2e, 0x6d, 0x73, 0x67, 0x2e,
	0x4d, 0x61, 0x74, 0x63, 0x68, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x14, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0f, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x12, 0x15, 0x2e,
	0x6d, 0x73, 0x67, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x11,
	0x4d, 0x61, 0x74, 0x63, 0x68, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x43, 0x61, 0x6e, 0x63, 0x65,
	0x6c, 0x12, 0x11, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x07,
	0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x13, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x4f, 0x66,
	0x66, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x6d,
	0x73, 0x67, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04, 0x2f, 0x6d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_room_proto_rawDescOnce sync.Once
	file_pb_room_proto_rawDescData = file_pb_room_proto_rawDesc
)

func file_pb_room_proto_rawDescGZIP() []byte {
	file_pb_room_proto_rawDescOnce.Do(func() {
		file_pb_room_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_room_proto_rawDescData)
	})
	return file_pb_room_proto_rawDescData
}

var file_pb_room_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_pb_room_proto_goTypes = []interface{}{
	(*CreateRoomRequest)(nil),  // 0: msg.CreateRoomRequest
	(*MatchRoomRequest)(nil),   // 1: msg.MatchRoomRequest
	(*OfflineRequest)(nil),     // 2: msg.OfflineRequest
	(*MatchMemberRequest)(nil), // 3: msg.MatchMemberRequest
	(*AddRequest)(nil),         // 4: msg.AddRequest
	(*LeaveRequest)(nil),       // 5: msg.LeaveRequest
	(*OverRequest)(nil),        // 6: msg.OverRequest
	(*Answer)(nil),             // 7: msg.Answer
	(*Question)(nil),           // 8: msg.Question
	(*Member)(nil),             // 9: msg.Member
	(*CreateRoomReply)(nil),    // 10: msg.CreateRoomReply
	(*RoomChangeState)(nil),    // 11: msg.RoomChangeState
}
var file_pb_room_proto_depIdxs = []int32{
	9,  // 0: msg.CreateRoomRequest.member:type_name -> msg.Member
	9,  // 1: msg.MatchMemberRequest.Member:type_name -> msg.Member
	9,  // 2: msg.AddRequest.member:type_name -> msg.Member
	9,  // 3: msg.LeaveRequest.member:type_name -> msg.Member
	9,  // 4: msg.OverRequest.member:type_name -> msg.Member
	9,  // 5: msg.Answer.Member:type_name -> msg.Member
	7,  // 6: msg.Member.Answer:type_name -> msg.Answer
	9,  // 7: msg.CreateRoomReply.PrepareMembers:type_name -> msg.Member
	9,  // 8: msg.CreateRoomReply.PlayingMembers:type_name -> msg.Member
	9,  // 9: msg.CreateRoomReply.ChangeMemeber:type_name -> msg.Member
	8,  // 10: msg.CreateRoomReply.Question:type_name -> msg.Question
	0,  // 11: msg.Room.Create:input_type -> msg.CreateRoomRequest
	4,  // 12: msg.Room.Add:input_type -> msg.AddRequest
	5,  // 13: msg.Room.Leave:input_type -> msg.LeaveRequest
	6,  // 14: msg.Room.Over:input_type -> msg.OverRequest
	7,  // 15: msg.Room.AnswerQuestion:input_type -> msg.Answer
	1,  // 16: msg.Room.MatchRoom:input_type -> msg.MatchRoomRequest
	3,  // 17: msg.Room.MatchMember:input_type -> msg.MatchMemberRequest
	1,  // 18: msg.Room.MatchRoomCancel:input_type -> msg.MatchRoomRequest
	5,  // 19: msg.Room.MatchMemberCancel:input_type -> msg.LeaveRequest
	2,  // 20: msg.Room.Offline:input_type -> msg.OfflineRequest
	10, // 21: msg.Room.Create:output_type -> msg.CreateRoomReply
	11, // 22: msg.Room.Add:output_type -> msg.RoomChangeState
	11, // 23: msg.Room.Leave:output_type -> msg.RoomChangeState
	11, // 24: msg.Room.Over:output_type -> msg.RoomChangeState
	11, // 25: msg.Room.AnswerQuestion:output_type -> msg.RoomChangeState
	11, // 26: msg.Room.MatchRoom:output_type -> msg.RoomChangeState
	11, // 27: msg.Room.MatchMember:output_type -> msg.RoomChangeState
	11, // 28: msg.Room.MatchRoomCancel:output_type -> msg.RoomChangeState
	11, // 29: msg.Room.MatchMemberCancel:output_type -> msg.RoomChangeState
	11, // 30: msg.Room.Offline:output_type -> msg.RoomChangeState
	21, // [21:31] is the sub-list for method output_type
	11, // [11:21] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_pb_room_proto_init() }
func file_pb_room_proto_init() {
	if File_pb_room_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_room_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_room_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchRoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_room_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OfflineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_room_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchMemberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_room_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_room_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_room_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OverRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_room_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Answer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_room_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Question); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_room_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Member); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_room_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRoomReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_room_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomChangeState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_room_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_room_proto_goTypes,
		DependencyIndexes: file_pb_room_proto_depIdxs,
		MessageInfos:      file_pb_room_proto_msgTypes,
	}.Build()
	File_pb_room_proto = out.File
	file_pb_room_proto_rawDesc = nil
	file_pb_room_proto_goTypes = nil
	file_pb_room_proto_depIdxs = nil
}
