// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: pb/storage.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginStorageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=Uuid,proto3" json:"Uuid,omitempty"`
	Uid  string `protobuf:"bytes,2,opt,name=Uid,proto3" json:"Uid,omitempty"`
}

func (x *LoginStorageRequest) Reset() {
	*x = LoginStorageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_storage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginStorageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginStorageRequest) ProtoMessage() {}

func (x *LoginStorageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_storage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginStorageRequest.ProtoReflect.Descriptor instead.
func (*LoginStorageRequest) Descriptor() ([]byte, []int) {
	return file_pb_storage_proto_rawDescGZIP(), []int{0}
}

func (x *LoginStorageRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *LoginStorageRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type SuccessStateReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State int32 `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *SuccessStateReply) Reset() {
	*x = SuccessStateReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_storage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SuccessStateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessStateReply) ProtoMessage() {}

func (x *SuccessStateReply) ProtoReflect() protoreflect.Message {
	mi := &file_pb_storage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessStateReply.ProtoReflect.Descriptor instead.
func (*SuccessStateReply) Descriptor() ([]byte, []int) {
	return file_pb_storage_proto_rawDescGZIP(), []int{1}
}

func (x *SuccessStateReply) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

type OffLineStorageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=Uuid,proto3" json:"Uuid,omitempty"`
}

func (x *OffLineStorageRequest) Reset() {
	*x = OffLineStorageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_storage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OffLineStorageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OffLineStorageRequest) ProtoMessage() {}

func (x *OffLineStorageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_storage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OffLineStorageRequest.ProtoReflect.Descriptor instead.
func (*OffLineStorageRequest) Descriptor() ([]byte, []int) {
	return file_pb_storage_proto_rawDescGZIP(), []int{2}
}

func (x *OffLineStorageRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type UpdateStorageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid  string `protobuf:"bytes,1,opt,name=Uuid,proto3" json:"Uuid,omitempty"`
	Uid   string `protobuf:"bytes,2,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Key   string `protobuf:"bytes,3,opt,name=Key,proto3" json:"Key,omitempty"`
	Value string `protobuf:"bytes,4,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *UpdateStorageRequest) Reset() {
	*x = UpdateStorageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_storage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateStorageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStorageRequest) ProtoMessage() {}

func (x *UpdateStorageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_storage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStorageRequest.ProtoReflect.Descriptor instead.
func (*UpdateStorageRequest) Descriptor() ([]byte, []int) {
	return file_pb_storage_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateStorageRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UpdateStorageRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *UpdateStorageRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UpdateStorageRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type PullStorageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=Uuid,proto3" json:"Uuid,omitempty"`
	Uid  string `protobuf:"bytes,2,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Key  string `protobuf:"bytes,3,opt,name=Key,proto3" json:"Key,omitempty"`
}

func (x *PullStorageRequest) Reset() {
	*x = PullStorageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_storage_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullStorageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullStorageRequest) ProtoMessage() {}

func (x *PullStorageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_storage_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullStorageRequest.ProtoReflect.Descriptor instead.
func (*PullStorageRequest) Descriptor() ([]byte, []int) {
	return file_pb_storage_proto_rawDescGZIP(), []int{4}
}

func (x *PullStorageRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *PullStorageRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *PullStorageRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type PullStorageReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *PullStorageReply) Reset() {
	*x = PullStorageReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_storage_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullStorageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullStorageReply) ProtoMessage() {}

func (x *PullStorageReply) ProtoReflect() protoreflect.Message {
	mi := &file_pb_storage_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullStorageReply.ProtoReflect.Descriptor instead.
func (*PullStorageReply) Descriptor() ([]byte, []int) {
	return file_pb_storage_proto_rawDescGZIP(), []int{5}
}

func (x *PullStorageReply) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_pb_storage_proto protoreflect.FileDescriptor

var file_pb_storage_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x62, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x3b, 0x0a, 0x13, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x55, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x55, 0x75,
	0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x55, 0x69, 0x64, 0x22, 0x29, 0x0a, 0x11, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22,
	0x2b, 0x0a, 0x15, 0x4f, 0x66, 0x66, 0x4c, 0x69, 0x6e, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x75, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x55, 0x75, 0x69, 0x64, 0x22, 0x64, 0x0a, 0x14,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x55, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x4c, 0x0a, 0x12, 0x50, 0x75, 0x6c, 0x6c, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x75, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x55, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x55, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x69, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79,
	0x22, 0x28, 0x0a, 0x10, 0x50, 0x75, 0x6c, 0x6c, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0x9c, 0x02, 0x0a, 0x07, 0x53,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x12, 0x42, 0x0a, 0x0c, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x53,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x12, 0x18, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x16, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0e, 0x4f, 0x66,
	0x66, 0x4c, 0x69, 0x6e, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x2e, 0x6d,
	0x73, 0x67, 0x2e, 0x4f, 0x66, 0x66, 0x4c, 0x69, 0x6e, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x53,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x12, 0x44, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x12, 0x19, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16,
	0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x0b, 0x50, 0x75, 0x6c, 0x6c,
	0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x12, 0x17, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x50, 0x75,
	0x6c, 0x6c, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x15, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x50, 0x75, 0x6c, 0x6c, 0x53, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04, 0x2f, 0x6d, 0x73,
	0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_storage_proto_rawDescOnce sync.Once
	file_pb_storage_proto_rawDescData = file_pb_storage_proto_rawDesc
)

func file_pb_storage_proto_rawDescGZIP() []byte {
	file_pb_storage_proto_rawDescOnce.Do(func() {
		file_pb_storage_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_storage_proto_rawDescData)
	})
	return file_pb_storage_proto_rawDescData
}

var file_pb_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pb_storage_proto_goTypes = []interface{}{
	(*LoginStorageRequest)(nil),   // 0: msg.LoginStorageRequest
	(*SuccessStateReply)(nil),     // 1: msg.SuccessStateReply
	(*OffLineStorageRequest)(nil), // 2: msg.OffLineStorageRequest
	(*UpdateStorageRequest)(nil),  // 3: msg.UpdateStorageRequest
	(*PullStorageRequest)(nil),    // 4: msg.PullStorageRequest
	(*PullStorageReply)(nil),      // 5: msg.PullStorageReply
}
var file_pb_storage_proto_depIdxs = []int32{
	0, // 0: msg.Storage.LoginStorage:input_type -> msg.LoginStorageRequest
	2, // 1: msg.Storage.OffLineStorage:input_type -> msg.OffLineStorageRequest
	3, // 2: msg.Storage.UpdateStorage:input_type -> msg.UpdateStorageRequest
	4, // 3: msg.Storage.PullStorage:input_type -> msg.PullStorageRequest
	1, // 4: msg.Storage.LoginStorage:output_type -> msg.SuccessStateReply
	1, // 5: msg.Storage.OffLineStorage:output_type -> msg.SuccessStateReply
	1, // 6: msg.Storage.UpdateStorage:output_type -> msg.SuccessStateReply
	5, // 7: msg.Storage.PullStorage:output_type -> msg.PullStorageReply
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_storage_proto_init() }
func file_pb_storage_proto_init() {
	if File_pb_storage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_storage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginStorageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_storage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SuccessStateReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_storage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OffLineStorageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_storage_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateStorageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_storage_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullStorageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_storage_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullStorageReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_storage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_storage_proto_goTypes,
		DependencyIndexes: file_pb_storage_proto_depIdxs,
		MessageInfos:      file_pb_storage_proto_msgTypes,
	}.Build()
	File_pb_storage_proto = out.File
	file_pb_storage_proto_rawDesc = nil
	file_pb_storage_proto_goTypes = nil
	file_pb_storage_proto_depIdxs = nil
}
