version: '3'
services:
  game1:
   image: "sheepserver:v1"
   restart: "unless-stopped"
   ports: 
      - 5101:5101
   command: /bin/sheep/runLeaf.sh :5101 "10.2.0.16:5000"
  game2:
   image: "sheepserver:v1"
   restart: "unless-stopped"
   ports: 
      - 5102:5102
   command: /bin/sheep/runLeaf.sh :5102 "10.2.0.16:5000"
  game3:
   image: "sheepserver:v1"
   restart: "unless-stopped"
   ports: 
      - 5103:5103
   command: /bin/sheep/runLeaf.sh :5103 "10.2.0.16:5000"
  game4:
   image: "sheepserver:v1"
   restart: "unless-stopped"
   ports: 
      - 5104:5104
   command: /bin/sheep/runLeaf.sh :5104 "10.2.0.16:5000"
  game5:
   image: "sheepserver:v1"
   restart: "unless-stopped"
   ports: 
      - 5105:5105
   command: /bin/sheep/runLeaf.sh :5105 "10.2.0.16:5000"
  game6:
   image: "sheepserver:v1"
   restart: "unless-stopped"
   ports: 
      - 5106:5106
   command: /bin/sheep/runLeaf.sh :5106 "10.2.0.16:5000"
  game7:
   image: "sheepserver:v1"
   restart: "unless-stopped"
   ports: 
      - 5107:5107
   command: /bin/sheep/runLeaf.sh :5107 "10.2.0.16:5000"
  game8:
   image: "sheepserver:v1"
   restart: "unless-stopped"
   ports: 
      - 5108:5108
   command: /bin/sheep/runLeaf.sh :5108 "10.2.0.16:5000"
networks:
 front-tier:
  driver: bridge
 back-tier:
  driver: bridge