# Version: 0. 0. 1

FROM centos:7
COPY ./*.sh /bin/sheep/
COPY ./bin/* /bin/sheep/bin/
COPY ./conf/* /bin/sheep/conf/
COPY ./table/* /bin/sheep/table/
COPY ./ssl/* /bin/sheep/ssl/
COPY ./IP2LOCATION-LITE-DB3.IPV6.BIN/* /bin/sheep/IP2LOCATION-LITE-DB3.IPV6.BIN/
COPY ./easygame2021.com_nginx/* /bin/sheep/easygame2021.com_nginx/
